# -*- coding: utf-8 -*-
"""Practica.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18qz93FqkJMarQ-95pg5M0Bd8E7WHJw0W
"""

import pandas as pd
import numpy as np
import random
from datetime import datetime, timedelta

# Configuración de semillas para reproducibilidad
np.random.seed(42)
random.seed(42)

# 1. Crear Dim_Productos (15 Productos)
productos = [
    ('P01', 'Laptop Pro 15', 'Tecnología', 800000, 1200000),
    ('P02', 'Monitor 27 IPS', 'Tecnología', 250000, 450000),
    ('P03', 'Teclado Mecánico', 'Tecnología', 60000, 110000),
    ('P04', 'Mouse Inalámbrico', 'Tecnología', 30000, 55000),
    ('P05', 'Audífonos Bluetooth', 'Tecnología', 90000, 180000),
    ('P06', 'Silla Ergonómica', 'Oficina', 180000, 320000),
    ('P07', 'Escritorio Ajustable', 'Oficina', 300000, 550000),
    ('P08', 'Lámpara LED LED', 'Oficina', 25000, 50000),
    ('P09', 'Impresora Láser', 'Oficina', 200000, 380000),
    ('P10', 'Cámara Web HD', 'Tecnología', 70000, 130000),
    ('P11', 'Disco Duro Externo 1TB', 'Tecnología', 110000, 190000),
    ('P12', 'Mochila para Laptop', 'Accesorios', 35000, 70000),
    ('P13', 'Soporte para Laptop', 'Accesorios', 20000, 45000),
    ('P14', 'Power Bank 20000mAh', 'Accesorios', 45000, 85000),
    ('P15', 'Hub USB-C 7 en 1', 'Accesorios', 50000, 95000)
]

df_productos = pd.DataFrame(productos, columns=[
    'ID_Producto', 'Nombre_Producto', 'Categoria', 'Costo_Unitario', 'Precio_Venta'
])

# 2. Crear Dim_Clientes (120 Clientes)
ciudades = ['Bogotá', 'Medellín', 'Cali', 'Barranquilla', 'Bucaramanga']
segmentos = ['Corporativo', 'Pyme', 'Consumidor Final']

clientes = []
for i in range(1, 121):
    clientes.append((
        f'C{i:03d}',
        f'Cliente {i}',
        random.choice(ciudades),
        random.choice(segmentos)
    ))

df_clientes = pd.DataFrame(clientes, columns=['ID_Cliente', 'Nombre_Cliente', 'Ciudad', 'Segmento'])

# 3. Crear Fact_Ventas (1,500 Transacciones entre 2025 y 2026)
num_ventas = 1500
fecha_inicio = datetime(2025, 1, 1)
canales = ['Tienda Física', 'Sitio Web', 'Distribuidor']

ventas = []
for i in range(1001, 1001 + num_ventas):
    fecha = fecha_inicio + timedelta(days=random.randint(0, 600))
    id_cliente = f'C{random.randint(1, 120):03d}'
    id_producto = f'P{random.randint(1, 15):02d}'
    cantidad = np.random.choice([1, 2, 3, 4, 5], p=[0.5, 0.25, 0.15, 0.07, 0.03])
    canal = random.choice(canales)

    ventas.append((i, fecha.strftime('%Y-%m-%d'), id_cliente, id_producto, cantidad, canal))

df_ventas = pd.DataFrame(ventas, columns=[
    'ID_Venta', 'Fecha', 'ID_Cliente', 'ID_Producto', 'Cantidad', 'Canal_Venta'
])

# 4. Exportar los tres datasets a CSV
df_ventas.to_csv('Fact_Ventas.csv', index=False)
df_productos.to_csv('Dim_Productos.csv', index=False)
df_clientes.to_csv('Dim_Clientes.csv', index=False)

print("¡Archivos generados exitosamente en la carpeta de Colab!")

